---
# Default variables for ACR role

# ACR connection details (populated by Terraform)
acr_login_server: ""
acr_username: ""
acr_password: ""
acr_name: ""

# Public images to pull and push to ACR (organized by folder)
public_images:
  - image: "docker.io/library/nginx:casopractico2"
    folder: "base"

# Podman binary path
podman_executable: "podman"
